// <auto-generated />
using System;
using DisasterApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisasterApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204054013_AddDefaultTimestamps")]
    partial class AddDefaultTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisasterApi.Models.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RequireResources")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TimeConstraint")
                        .HasColumnType("integer");

                    b.Property<int>("UrgentyLevel")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("DisasterApi.Models.Assignment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("AreaID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RequireDelivered")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TruckID")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("AreaID");

                    b.HasIndex("TruckID");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("DisasterApi.Models.Truck", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("AvailableResources")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TravelTimeToArea")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("DisasterApi.Models.Assignment", b =>
                {
                    b.HasOne("DisasterApi.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisasterApi.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Truck");
                });
#pragma warning restore 612, 618
        }
    }
}
